[project]
name = "openclip-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clip-benchmark>=1.6.2",
    "open-clip-torch>=3.0.0",
    "pycocotools>=2.0.10",
    "skypilot>=0.10.0",
]
