name: experiment-eva-mscoco-spot

resources:
  # Let SkyPilot find the best available GPU across all clouds
  accelerators: {
    H200:1,           # 141GB - Best for largest models
    H100:1,           # 80GB
    A100-80GB:1,      # 80GB
    A100:1,           # 40GB
    L40S:1,           # 48GB
    L40:1,            # 48GB
    L4:1,             # 24GB - Minimum for most models
    RTX6000-Ada:1,    # 48GB
    RTXA6000:1,       # 48GB
    RTX4090:1,        # 24GB
  }
  
  # Try all cloud and spot combinations
  any_of:
    - {infra: lambda, use_spot: false}  # Lambda doesn't support spot
    - {infra: runpod, use_spot: true}
    - {infra: runpod, use_spot: false}
    - {infra: nebius, use_spot: false}  # Nebius doesn't support spot

workdir: .

setup: |
  uv sync

run: |
  echo "Starting benchmark: EVA01-g-14/laion400m_s11b_b41k on mscoco_captions (zeroshot_retrieval)"
  start_time=$(date +%s)
  
  uv run clip_benchmark eval \
    --pretrained_model EVA01-g-14,laion400m_s11b_b41k \
    --dataset wds/mscoco_captions \
    --dataset_root "https://huggingface.co/datasets/clip-benchmark/wds_mscoco_captions/tree/main" \
    --task zeroshot_retrieval \
    --batch_size 16 \
    --output "/clip_eval_runner_results/{dataset}_{pretrained}_{model}_{language}_{task}.json"
  
  end_time=$(date +%s)
  runtime=$((end_time - start_time))
  echo "Benchmark completed in $runtime seconds ($((runtime / 60)) minutes)"
  echo "Result saved to: /clip_eval_runner_results/{dataset}_{pretrained}_{model}_{language}_{task}.json"

