name: clip-eval-runner-group-{job_id}

resources:
  # Let SkyPilot find the best available GPU across all clouds
  accelerators: {
    H200:1,           # 141GB - Best for largest models
    H100:1,           # 80GB
    A100-80GB:1,      # 80GB
    A100:1,           # 40GB
    L40S:1,           # 48GB
    L40:1,            # 48GB
    L4:1,             # 24GB - Minimum for most models
    RTX6000-Ada:1,    # 48GB
    RTXA6000:1,       # 48GB
    RTX4090:1,        # 24GB
  }
  
  # Try all cloud and spot combinations
  any_of:
    - {infra: lambda, use_spot: false}  # Lambda doesn't support spot
    # - {infra: runpod, use_spot: true}   # Temporarily disabled - hanging issue
    # - {infra: runpod, use_spot: false}  # Temporarily disabled - hanging issue
    - {infra: nebius, use_spot: false}  # Nebius doesn't support spot
  
  disk_size: 100

workdir: .

setup: |
  uv sync
  
  # Install AWS CLI v2
  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  unzip awscliv2.zip
  sudo ./aws/install
  rm -rf awscliv2.zip aws/
  
  # Create local output directory
  mkdir -p ~/clip_eval_runner_results

run: |
  # Always write to local directory
  # Results are synced to R2 after each benchmark for fault tolerance
  uv run python scripts/run_benchmark_group.py \
    --model "{model}" \
    --pretrained "{pretrained}" \
    --output-dir "$HOME/clip_eval_runner_results" \
    {max_benchmarks_flag}

envs:
  # R2 credentials - these must be set in your environment before launching
  # SkyPilot will automatically pass through these from your local environment
  R2_ENDPOINT_URL: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  HF_TOKEN: ${HF_TOKEN}
  HF_HUB_OFFLINE: ${HF_HUB_OFFLINE}