name: openclip-group-{job_id}

resources:
  # Let SkyPilot find the best available GPU across all clouds
  accelerators: {
    H200:1,           # 141GB - Best for largest models
    H100:1,           # 80GB
    A100-80GB:1,      # 80GB
    A100:1,           # 40GB
    L40S:1,           # 48GB
    L40:1,            # 48GB
    L4:1,             # 24GB - Minimum for most models
    RTX6000-Ada:1,    # 48GB
    RTXA6000:1,       # 48GB
    RTX4090:1,        # 24GB
  }
  
  # Try all cloud and spot combinations
  any_of:
    - {infra: lambda, use_spot: false}  # Lambda doesn't support spot
    - {infra: runpod, use_spot: true}
    - {infra: runpod, use_spot: false}
    - {infra: nebius, use_spot: false}  # Nebius doesn't support spot
  
  disk_size: 50

workdir: .

setup: |
  uv sync
  # Create local output directory
  mkdir -p ~/openclip_results

run: |
  # Always write to local directory
  uv run python scripts/run_benchmark_group.py \
    --model "{model}" \
    --pretrained "{pretrained}" \
    --output-dir "$HOME/openclip_results"
  
  # Sync results to R2
  echo "Syncing results to R2..."
  aws s3 sync ~/openclip_results/ s3://openclip-results/ \
    --endpoint-url $R2_ENDPOINT_URL \
    --region auto

envs:
  # Model information for debugging
  MODEL: {model}
  PRETRAINED: {pretrained}