resources:
  # 1x NVIDIA A100 GPU
  accelerators: A100:1

# Working directory (optional) containing the project codebase.
# Its contents are synced to ~/sky_workdir/ on the cluster.
workdir: .

# Typical use: pip install -r requirements.txt
# Invoked under the workdir (i.e., can use its files).
setup: |
  echo "Running setup."
  uv sync

# Typical use: make use of resources, such as running training.
# Invoked under the workdir (i.e., can use its files).
run: |
  echo "Hello, SkyPilot!"
  uv pip list

# Create an empty r2 bucket
file_mounts:
  /openclip_results:
    name: openclip-results
    store: r2 
