name: openclip-benchmark-{job_id}

resources:
  accelerators: {gpu_type}
  use_spot: {use_spot}
  disk_size: {disk_size}

# Working directory containing the project codebase
workdir: .

file_mounts:
  /openclip_results:
    name: openclip-results
    store: r2

setup: |
  uv sync

run: |
  uv run clip_benchmark eval \
    --pretrained_model {model},{pretrained} \
    --dataset {dataset} \
    --dataset_root "{dataset_root}" \
    --task {task_type} \
    --output "/openclip_results/{dataset}_{pretrained}_{model}_{language}_{task}.json"

envs:
  MODEL: {model}
  PRETRAINED: {pretrained}
  DATASET: {dataset}
  DATASET_ROOT: {dataset_root}
  TASK_TYPE: {task_type}